// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SampleloginTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless");
        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void samplelogin() {
        // Test name: sample-login
        // Step # | name | target | value | comment
        // 1 | open | /login |  |
        driver.get("http://localhost:8081/login");
        // 2 | setWindowSize | 1279x1375 |  |
        driver.manage().window().setSize(new Dimension(1279, 1375));
        // 3 | click | name=username |  |
        driver.findElement(By.name("username")).click();
        // 4 | type | name=username | a@localhost.de |
        driver.findElement(By.name("username")).sendKeys("a@localhost.de");
        // 5 | click | name=password |  |
        driver.findElement(By.name("password")).click();
        // 6 | type | name=password | a |
        driver.findElement(By.name("password")).sendKeys("a");
        // 7 | click | css=.row |  |
        driver.findElement(By.cssSelector(".row")).click();
        // 8 | click | name=submit |  |
        driver.findElement(By.name("submit")).click();
    }
}
